### ISSUE TITLE
Support for akka 2.5 and scala 2.11

### ISSUE THREAD

**Issue by OlafurD** [enragedginger/akka-quartz-scheduler#66] opened 2018-01-09 14:41 UTC
Is it possible to support akka 2.5 with scala 2.11?

**Comment by urieli** [comment] 2018-01-30 15:11
See https://github.com/enragedginger/akka-quartz-scheduler/issues/64

**Comment by enragedginger** [comment] 2018-01-30 15:29
Hi @OlafurD, @urieli is correct, this is a duplicate of #64. You should be able to use the Akka 2.4, Scala 2.11 build of the project just fine with Akka 2.5.

**Closed by enragedginger** 2018-01-30 15:29 UTC
